TensorQTL uses T Distributions when calculating P value. 
LiteQTL calculates LOD score. 
So the purpose of this notebook is to convert the output of LiteQTL from LOD score to P value. 
And make comparison, to see if results agree.

In [15]:
using Distributions

In [1]:
using DelimitedFiles 
using Distributions

In [2]:
pyresult = readdlm("tensorqtl-scan-covar.csv", ',')

2974×19837 Array{Any,2}:
 "variant_id"              "ENSG00000227232.5"  …   "ENSG00000182484.15"
 "chr9_10362_C_CT_b38"    0.626653                 0.209702
 "chr9_10469_G_C_b38"     0.331559                 0.356387
 "chr9_14690_C_G_b38"     0.196573                 0.334393
 "chr9_14889_A_G_b38"     0.000198589              0.574056
 "chr9_15883_A_G_b38"     0.514378              …  0.159159
 "chr9_16934_G_A_b38"     0.921802                 0.279384
 "chr9_16967_A_G_b38"     0.00620114               0.626413
 "chr9_17107_T_C_b38"     0.871817                 0.596388
 "chr9_17115_G_C_b38"     4.44153e-5               0.607573
 "chr9_17333_A_G_b38"     6.73954e-5            …  0.439791
 "chr9_17517_C_T_b38"     0.172699                 0.11458
 "chr9_17614_CT_C_b38"    0.00224832               0.803634
 ⋮                                              ⋱  
 "chr9_683402_C_T_b38"    0.20921                  0.254453
 "chr9_683423_T_C_b38"    4.06184e-8               0.000480425
 "chr9_6

In [3]:
jucresult = readdlm("julia-scan-pval-result-cpu.csv", ',')

19836×2973 Array{Float64,2}:
 0.626652    0.626652    0.626652    …  0.626652    0.626652    0.626652
 0.423787    0.423787    0.423787       0.423787    0.423787    0.423787
 0.456766    0.456766    0.456766       0.456766    0.456766    0.456766
 0.617429    0.617429    0.617429       0.617429    0.617429    0.617429
 0.209932    0.209932    0.209932       0.209932    0.209932    0.209932
 0.0139409   0.0139409   0.0139409   …  0.0139409   0.0139409   0.0139409
 0.626792    0.626792    0.626792       0.626792    0.626792    0.626792
 0.828035    0.828035    0.828035       0.828035    0.828035    0.828035
 0.759537    0.759537    0.759537       0.759537    0.759537    0.759537
 0.00378155  0.00378155  0.00378155     0.00378155  0.00378155  0.00378155
 0.866619    0.866619    0.866619    …  0.866619    0.866619    0.866619
 0.445077    0.445077    0.445077       0.445077    0.445077    0.445077
 0.432648    0.432648    0.432648       0.432648    0.432648    0.432648
 ⋮                 

In [15]:
pyp = convert(Matrix{Float64}, transpose(pyresult[2:end, 2:end]))

LoadError: InterruptException:

In [19]:
sum(isapprox.(jucresult[1:99, 1], pyp[1:99, 1], atol=1e-3)) == 99

true

In [18]:
jucresult[1:99, 1]

99×99 Array{Float64,2}:
 0.626652    0.626652    0.626652    …  0.626652    0.626652    0.626652
 0.423787    0.423787    0.423787       0.423787    0.423787    0.423787
 0.456766    0.456766    0.456766       0.456766    0.456766    0.456766
 0.617429    0.617429    0.617429       0.617429    0.617429    0.617429
 0.209932    0.209932    0.209932       0.209932    0.209932    0.209932
 0.0139409   0.0139409   0.0139409   …  0.0139409   0.0139409   0.0139409
 0.626792    0.626792    0.626792       0.626792    0.626792    0.626792
 0.828035    0.828035    0.828035       0.828035    0.828035    0.828035
 0.759537    0.759537    0.759537       0.759537    0.759537    0.759537
 0.00378155  0.00378155  0.00378155     0.00378155  0.00378155  0.00378155
 0.866619    0.866619    0.866619    …  0.866619    0.866619    0.866619
 0.445077    0.445077    0.445077       0.445077    0.445077    0.445077
 0.432648    0.432648    0.432648       0.432648    0.432648    0.432648
 ⋮                      

In [16]:
pyp = convert(Matrix{Float64}, transpose(pyresult[2:100, 2:100]))

99×99 Array{Float64,2}:
 0.626653    0.331559   0.196573     …  0.00142707   4.49919e-7   0.0840266
 0.423788    0.448207   0.0613929       0.552967     0.0179778    0.408914
 0.456767    0.725417   0.0109171       0.65361      0.0175027    0.966689
 0.61743     0.531565   0.00550506      0.122352     7.10107e-5   0.224221
 0.209933    0.483162   0.023176        0.923178     0.636353     0.786854
 0.0139411   0.0281532  0.120904     …  0.000559783  0.0186721    0.89146
 0.626793    0.430577   0.00908082      0.00619864   1.03677e-5   0.380858
 0.828036    0.891162   0.0583351       0.186957     0.0113238    0.212167
 0.759537    0.410551   0.080064        0.365965     1.95733e-5   0.0140823
 0.00378162  0.871401   0.328583        0.105253     0.825004     0.487983
 0.866619    0.715931   0.463061     …  0.690922     0.0369716    0.135111
 0.445078    0.98966    0.428138        0.77184      0.584713     0.669345
 0.432648    0.321818   0.158662        0.304824     0.375296     0.176224


# Testing function with basic numbers. 

In [25]:
function center_normalize(mat, dims=1)
    newmat = mat .- mean(mat, dims=dims)
    return newmat ./ sqrt.(sum(newmat.^2, dims=dims))
end
function calculate_r_tensor(geno, pheno; has_covar=false)
    # remove mean from geno and pheno
    if has_covar
        pheno = pheno.mean(dims = 1) 
        geno = geno.mean(dims = 1)
    end
    return center_normalize(pheno, 1)' * center_normalize(geno, 1)
end
function pval_calc(corr, dof)
    t = corr .* sqrt.(dof ./ (1 .- corr .^2))
    pval = 2 .* cdf(TDist(dof), .-abs.(t))
    return pval
end

pval_calc (generic function with 1 method)

In [28]:
# Start with correlation matrix. This is just a random matrix. Nothing special
geno = [0.1 0.2 0.3; 0.4 0.5 0.6]

pheno = [1.1 2.2 3.3 4.4; 5.5 6.6 7.7 8.8]
# Degree of freedom should be n - 1
mydof = size(r, 1) - 1

r = calculate_r_tensor(geno, pheno)
pval = pval_calc(r, mydof)

4×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [34]:


res = pval_calc(r, 3)


Corr:
[0.1 0.2 0.3; 0.4 0.5 0.6]
tstat:
[0.17407765595569785 0.3535533905932738 0.5447047794019222; 0.7559289460184545 1.0 1.299038105676658]
Pval:
[0.8728885715695383 0.7470600781046619 0.6238376647810728; 0.5046315754686909 0.39100221895577053 0.28475697986529375]


2×3 Array{Float64,2}:
 0.872889  0.74706   0.623838
 0.504632  0.391002  0.284757

In [ ]:
using StatsBase

function getGenoidx(GenoData::Array{Float32,2}, maf_threshold::Float32=Float32(0.025)) 
#     print("---- mean/2: ")
    af = mean(GenoData,dims=2)/2.0
    maf = replace(x -> x > 0.5 ? 1-x : x, af)
    return getindex.(findall(maf.>= maf_threshold),1) 
end

function filter_maf(genotype::Array{Float32, 2})
    alleles = 2
    maf_threshold = Float32(0.05)
    
    af = sum(genotype, dims=2) ./ (alleles * size(genotype, 2))
    maf = replace(x -> x > 0.5 ? 1-x : x, af)

    if maf_threshold > 0 
        mask = getindex.(findall(maf .>= maf_threshold), 1)
        genotype = genotype[mask, :]
    end
    return genotype
end

genotype = convert(Matrix{Float32}, [0.04 0.05 0.06; 0.08 0.1 0.12])
print(getGenoidx(genotype, 0.05f0))
println("---- Starting filter_maf -----")
print(filter_maf(genotype))

# print(genotype)
# print(maf)

filtered = getGenoidx(G_t, 0.05f0);
filtered2 = filter_maf(G_t)
print(size(filtered)) 
print(size(filtered2)) 

### Graveyard. 
Functions that I tried but didn't work. Keeping them in here for now. Can be cleaned up anytime!

In [16]:
# Saunak send me this function to convert 
function lod2p(lod)
    mylod = 2*log(10)*lod
    mycdf = cdf(Chisq(1), mylod)
    print(mycdf)
    return 1 .- mycdf
end
pval_l = lod2p(r)

1

In [17]:
#TensorQTL version:
function lod2p_t(lod)
    2*stats.t.cdf(-np.abs(res[:,2].astype(np.float64)), dof)

[0.502617557044459 0.662796385726653 0.7601628772665022; 0.8252912503937563 0.870841121301594 0.9035389721707014]

2×3 Array{Float64,2}:
 0.497382  0.337204  0.239837
 0.174709  0.129159  0.096461

In [18]:
ans

2×3 Array{Float64,2}:
 0.497382  0.337204  0.239837
 0.174709  0.129159  0.096461

In [14]:
# LiteQTL version: 
cdf(r[:, 1], dof)

LoadError: MethodError: no method matching cdf(::Array{Float64,1}, ::Int64)
Closest candidates are:
  cdf(::DiscreteUniform, ::Int64) at /home/xiaoqihu/.julia/packages/Distributions/cNe2C/src/univariate/discrete/discreteuniform.jl:73
  cdf(::Hypergeometric, ::Int64) at /home/xiaoqihu/.julia/packages/Distributions/cNe2C/src/univariates.jl:550
  cdf(::Chernoff, ::Real) at /home/xiaoqihu/.julia/packages/Distributions/cNe2C/src/univariate/continuous/chernoff.jl:170
  ...